### ISSUE TITLE
Faltando a palavra versionamento

### ISSUE THREAD

**Issue by amdrade** [rafaelsc/IntelliJ.Portuguese.Brazil.Dictionary#13]
Falta a palavra versionamento

**Comment by ricardomalias** [comment]
adicionei o pull request sobre isso, espero que ajude

https://github.com/rafaelsc/IntelliJ.Portuguese.Brazil.Dictionary/pull/17

**Comment by rafaelsc** [comment]
PR Aceito e Mesclado.
