### ISSUE TITLE
Não está funcionando no PhpStorm 2021.2

### ISSUE THREAD

**Issue by jonasmarco** [rafaelsc/IntelliJ.Portuguese.Brazil.Dictionary#18]
Instalei o dicionário na versão mais recente do PhpStorm mas não está funcionando, antes de atualizar sim.

![image](https://user-images.githubusercontent.com/19959770/127664870-5dc7932d-b701-46bf-ab9c-fa239d1eb22f.png)

![image](https://user-images.githubusercontent.com/19959770/127665000-24096380-8cbc-472a-9401-372a7525fff8.png)

![image](https://user-images.githubusercontent.com/19959770/127665081-b8e3a959-0030-47c3-b066-c96d171a0d20.png)

**Comment by MarioGK** [comment]
Esta acontecendo o mesmo comigo

**Comment by pealthoff** [comment]
Também no Android Studio 2020.3.1
